name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Native Image (containerized)
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -f docker/Dockerfile.lambda-native \
            --load \
            -t ops-lambda:ci .
